
[description]
name = "debian12"
virtio_name = ""
virtio_url = ""
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
answerfile = "preseed_on_enc_dhcp.cfg"
path_postinstall = ""
file_postinstall = "postinstall.bash"

[run]
vmname = "debian12-test"
