[description]
name = "ceph-p1"

[addon_answerfile]
host_name = "ceph-p1"
host_domain = "local"
net_ip = "10.10.123.81"

[[env]]
"MANAGE_HOST" = "ceph-p1"
"MANAGE_IP" = "10.10.123.81"
"HB_IP" = "10.20.124.81"
"STORAGE_IP" = "10.20.125.81"

[run]
vmname = "ceph-p1"
net_devs = [
  [
    "tap1-cp1",
    "vmbr1",
  ],
  [
    "tap2-cp1",
    "vmbr2",
  ],
  [
    "tap3-cp1",
    "vmbr3",
  ],
  [
    "tap4-cp1",
    "vmbr4",
  ],
]
