
[description]
name = "ceph"
virtio_name = ""
virtio_url = ""
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
answerfile = "preseed_off_no_enc.cfg"
path_postinstall = "postinstall"
file_postinstall = "postinstall.bash"

[run]
vmname = "cephbase"
net_prepare_fw = true
net_prepare_nics = true
net_prepare_bridges = false
res_cpu = 1
res_mem = 4096
disks = [
  [
    "os-hdd0.qcow2",
    "64G",
    "hdd",
    "none",
  ],
  [
    "ceph-hdd1.qcow2",
    "64G",
    "hdd",
    "none",
  ],
  [
    "ceph-hdd2.qcow2",
    "64G",
    "hdd",
    "none",
  ],
  [
    "ceph-nvme1.raw",
    "32G",
    "nvme",
    "none",
  ],
  [
    "ceph-nvme2.raw",
    "32G",
    "nvme",
    "none",
  ],
]
net_bridges = [
  [
    "vmbr1",
    "10.10.123.1",
    "24",
    true,
  ],
  [
    "vmbr2",
    "10.10.124.1",
    "24",
    true,
  ],
  [
    "vmbr3",
    "10.20.125.1",
    "24",
    true,
  ],
  [
    "vmbr4",
    "10.20.126.1",
    "24",
    true,
  ],
]
net_devs = [
  [
    "tap1-ceph",
    "vmbr1",
  ],
  [
    "tap2-ceph",
    "vmbr2",
  ],
  [
    "tap3-ceph",
    "vmbr3",
  ],
  [
    "tap4-ceph",
    "vmbr4",
  ],
]
[addon_postinstall]
joblist_early = []
joblist_late = ["/opt/umi/postinstall/installer/postinstall_ceph_install.bash"]
copy_additional_scripts = [
  "installer/default/offline_packages.bash",
  "installer/cluster/hostnet.bash",
  "installer/cluster/hostnames.bash",
  "installer/cluster/apt.bash",
  "installer/default/ssh.bash",
  "installer/default/locale.bash",
]

[addon_answerfile]
host_name = "ceph"
host_domain = "local"
net_dhcp = true
net_ip = "10.10.123.80"
net_mask = "255.255.255.0"
net_gateway = "10.10.123.1"
net_dns = "8.8.8.8"
include_offline_packages = ["ifenslave", "vlan"]
packages_install = ["openssh-server"]

[[env]]
"CEPH_UI_PASSWORD" = "aaa12345"
"ISO_TARGET_TYPE" = "vm"
"MANAGE_NET" = "10.10.123"
"MANAGE_IP" = "10.10.123.80"
"MANAGE_HOST" = "ceph-p0"
"MANAGE_DOMAIN" = "manage"
"MANAGE_GW" = "10.10.123.1"
"MANAGE_NS1" = "8.8.8.8"
"MANAGE_NS2" = "8.8.4.4"
"PROXY_IP" = "10.10.123.1:3128"
"TIME_IP" = "10.10.123.1"
"STORAGE_NET" = "10.20.125"
"STORAGE_IP" = "10.20.125.80"
"HB_NET" = "10.20.124"
"HB_IP" = "10.20.124.80"
"BOND0_NAME" = "bond0"
"BOND1_NAME" = "bond1"
"BRIDGE0_NAME" = "vmbr0"
"BRIDGE1_NAME" = "vmbr1"
"INTERFACE_BOND0_0" = "enp0s10"
"INTERFACE_BOND0_1" = "enp0s11"
"INTERFACE_BOND1_0" = "enp0s12"
"INTERFACE_BOND1_1" = "enp0s13"
"VLAN_HEARTBEAT" = "124"
"VLAN_STORAGE" = "125"
"INTERFACE_VLAN_HEARTBEAT" = "vlan124"
"INTERFACE_VLAN_STORAGE" = "vlan125"
"DISKNAME_PRIMARY" = "/dev/vda"
"DEFAULT_LEADER_PROXMOX" = "proxmox-h1"
"DEFAULT_LEADER_CEPH" = "ceph-s1"
"NODES_PROX_MANAGE_FQDN" = "proxmox-p1.manage,proxmox-p2.manage"
"NODES_PROX_MANAGE_NAME" = "proxmox-p1,proxmox-p2"
"NODES_PROX_MANAGE_IP" = "10.10.123.93,10.10.123.95"
"NODES_PROX_HB_FQDN" = "proxmox-h1.hb,proxmox-h2.hb"
"NODES_PROX_HB_NAME" = "proxmox-h1,proxmox-h2"
"NODES_PROX_HB_IP" = "10.20.124.93,10.20.124.95"
"NODES_PROX_STORAGE_FQDN" = "proxmox-s1.storage,proxmox-s2"
"NODES_PROX_STORAGE_NAME" = "proxmox-s1,proxmox-s2"
"NODES_PROX_STORAGE_IP" = "10.20.125.93,10.20.125.95"
"NODES_CEPH_MANAGE_FQDN" = "ceph-p1.manage,ceph-p2.manage"
"NODES_CEPH_MANAGE_NAME" = "ceph-p1,ceph-p2"
"NODES_CEPH_MANAGE_IP" = "10.10.123.101,10.10.123.102"
"NODES_CEPH_HB_FQDN" = "ceph-h1.hb,ceph-h2.hb"
"NODES_CEPH_HB_NAME" = "ceph-h1,ceph-h2"
"NODES_CEPH_HB_IP" = "10.20.124.101,10.20.124.102"
"NODES_CEPH_STORAGE_FQDN" = "ceph-s1.storage,ceph-s2.storage"
"NODES_CEPH_STORAGE_NAME" = "ceph-s1,ceph-s2"
"NODES_CEPH_STORAGE_IP" = "10.20.125.101,10.20.125.102"


# "NODES_PROX_MANAGE_FQDN" = "proxmox-p1.manage,proxmox-p2.manage,proxmox-p3.manage,proxmox-p4.manage,proxmox-p5.manage,proxmox-p6.manage,proxmox-p7.manage,proxmox-p8.manage,proxmox-p9.manage,proxmox-p10.manage,proxmox-p11.manage,proxmox-p12.manage,proxmox-p13.manage"
# "NODES_PROX_MANAGE_NAME" = "proxmox-p1,proxmox-p2,proxmox-p3,proxmox-p4,proxmox-p5,proxmox-p6,proxmox-p7,proxmox-p8,proxmox-p9,proxmox-p10,proxmox-p11,proxmox-p12,proxmox-p13"
# "NODES_PROX_MANAGE_IP" = "10.10.123.93,10.10.123.95,10.10.123.97,10.10.123.99,10.10.123.101,10.10.123.103,10.10.123.105,10.10.123.107,10.10.123.109,10.10.123.111,10.10.123.113,10.10.123.115,10.10.123.117"
# "NODES_PROX_HB_FQDN" = "proxmox-h1.hb,proxmox-h2.hb,proxmox-h3.hb,proxmox-h4.hb,proxmox-h5.hb,proxmox-h6.hb,proxmox-h7.hb,proxmox-h8.hb,proxmox-h9.hb,proxmox-h10.hb,proxmox-h11.hb,proxmox-h12.hb,proxmox-h13.hb"
# "NODES_PROX_HB_NAME" = "proxmox-h1,proxmox-h2,proxmox-h3,proxmox-h4,proxmox-h5,proxmox-h6,proxmox-h7,proxmox-h8,proxmox-h9,proxmox-h10,proxmox-h11,proxmox-h12,proxmox-h13"
# "NODES_PROX_HB_IP" = "10.20.124.93,10.20.124.95,10.20.124.97,10.20.124.99,10.20.124.101,10.20.124.103,10.20.124.105,10.20.124.107,10.20.124.109,10.20.124.111,10.20.124.113,10.20.124.115,10.20.124.117"
# "NODES_PROX_STORAGE_FQDN" = "proxmox-s1.storage,proxmox-s2.storage,proxmox-s3.storage,proxmox-s4.storage,proxmox-s5.storage,proxmox-s6.storage,proxmox-s7.storage,proxmox-s8.storage,proxmox-s9.storage,proxmox-s10.storage,proxmox-s11.storage,proxmox-s12.storage,proxmox-s13.storage"
# "NODES_PROX_STORAGE_NAME" = "proxmox-s1,proxmox-s2,proxmox-s3,proxmox-s4,proxmox-s5,proxmox-s6,proxmox-s7,proxmox-s8,proxmox-s9,proxmox-s10,proxmox-s11,proxmox-s12,proxmox-s13"
# "NODES_PROX_STORAGE_IP" = "10.20.125.93,10.20.125.95,10.20.125.97,10.20.125.99,10.20.125.101,10.20.125.103,10.20.125.105,10.20.125.107,10.20.125.109,10.20.125.111,10.20.125.113,10.20.125.115,10.20.125.117"
# "NODES_CEPH_MANAGE_FQDN" = "ceph-p1.manage,ceph-p2.manage,ceph-p3.manage,ceph-p4.manage,ceph-p5.manage,ceph-p6.manage,ceph-p7.manage,ceph-p8.manage,ceph-p9.manage,ceph-p10.manage,ceph-p11.manage,ceph-p12.manage,ceph-p13.manage"
# "NODES_CEPH_MANAGE_NAME" = "ceph-p1,ceph-p2,ceph-p3,ceph-p4,ceph-p5,ceph-p6,ceph-p7,ceph-p8,ceph-p9,ceph-p10,ceph-p11,ceph-p12,ceph-p13"
# "NODES_CEPH_MANAGE_IP" = "10.10.123.101,10.10.123.102,10.10.123.103,10.10.123.104,10.10.123.105,10.10.123.106,10.10.123.107,10.10.123.108,10.10.123.109,10.10.123.110,10.10.123.111,10.10.123.112,10.10.123.113"
# "NODES_CEPH_HB_FQDN" = "ceph-h1.hb,ceph-h2.hb,ceph-h3.hb,ceph-h4.hb,ceph-h5.hb,ceph-h6.hb,ceph-h7.hb,ceph-h8.hb,ceph-h9.hb,ceph-h10.hb,ceph-h11.hb,ceph-h12.hb,ceph-h13.hb"
# "NODES_CEPH_HB_NAME" = "ceph-h1,ceph-h2,ceph-h3,ceph-h4,ceph-h5,ceph-h6,ceph-h7,ceph-h8,ceph-h9,ceph-h10,ceph-h11,ceph-h12,ceph-h13"
# "NODES_CEPH_HB_IP" = "10.20.124.101,10.20.124.102,10.20.124.103,10.20.124.104,10.20.124.105,10.20.124.106,10.20.124.107,10.20.124.108,10.20.124.109,10.20.124.110,10.20.124.111,10.20.124.112,10.20.124.113"
# "NODES_CEPH_STORAGE_FQDN" = "ceph-s1.storage,ceph-s2.storage,ceph-s3.storage,ceph-s4.storage,ceph-s5.storage,ceph-s6.storage,ceph-s7.storage,ceph-s8.storage,ceph-s9.storage,ceph-s10.storage,ceph-s11.storage,ceph-s12.storage,ceph-s13.storage"
# "NODES_CEPH_STORAGE_NAME" = "ceph-s1,ceph-s2,ceph-s3,ceph-s4,ceph-s5,ceph-s6,ceph-s7,ceph-s8,ceph-s9,ceph-s10,ceph-s11,ceph-s12,ceph-s13"
# "NODES_CEPH_STORAGE_IP" = "10.20.125.101,10.20.125.102,10.20.125.103,10.20.125.104,10.20.125.105,10.20.125.106,10.20.125.107,10.20.125.108,10.20.125.109,10.20.125.110,10.20.125.111,10.20.125.112,10.20.125.113"
