[description]
name = "ceph-p9"

[addon_answerfile]
host_name = "ceph-p9"
host_domain = "local"
net_ip = "10.10.123.109"

[[env]]
"MANAGE_HOST" = "ceph-p9"
"MANAGE_IP" = "10.10.123.109"
"HB_IP" = "10.20.124.109"
"STORAGE_IP" = "10.20.125.109"

[run]
vmname = "ceph-p9"
net_devs = [
  [
    "tap1-cp9",
    "vmbr1",
  ],
  [
    "tap2-cp9",
    "vmbr2",
  ],
  [
    "tap3-cp9",
    "vmbr3",
  ],
  [
    "tap4-cp9",
    "vmbr4",
  ],
]
