[description]
name = "ceph-p2"

[addon_answerfile]
host_name = "ceph-p2"
host_domain = "local"
net_ip = "10.10.123.83"

[[env]]
"MANAGE_HOST" = "ceph-p2"
"MANAGE_IP" = "10.10.123.83"
"HB_IP" = "10.20.124.83"
"STORAGE_IP" = "10.20.125.83"

[run]
vmname = "ceph-p2"
net_devs = [
  [
    "tap1-cp2",
    "vmbr1",
  ],
  [
    "tap2-cp2",
    "vmbr2",
  ],
  [
    "tap3-cp2",
    "vmbr3",
  ],
  [
    "tap4-cp2",
    "vmbr4",
  ],
]
