[description]
name = "ceph-p4"

[addon_answerfile]
host_name = "ceph-p4"
host_domain = "local"
net_ip = "10.10.123.87"

[[env]]
"MANAGE_HOST" = "ceph-p4"
"MANAGE_IP" = "10.10.123.87"
"HB_IP" = "10.20.124.87"
"STORAGE_IP" = "10.20.125.87"

[run]
vmname = "ceph-p4"
net_devs = [
  [
    "tap1-cp4",
    "vmbr1",
  ],
  [
    "tap2-cp4",
    "vmbr2",
  ],
  [
    "tap3-cp4",
    "vmbr3",
  ],
  [
    "tap4-cp4",
    "vmbr4",
  ],
]
