
[description]
name = "ceph"
virtio_name = ""
virtio_url = ""
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
answerfile = "preseed_offline_no_enc.cfg"
path_postinstall = "postinstall"
file_postinstall = "postinstall.bash"

[run]
vmname = "cephbase"
disks = ["disk1.qcow2", "disk2.qcow2", "disk3.qcow2"]
net_ports = [[2220, 22]]
net_prepare_fw = false
net_prepare_nics = true
net_prepare_bridges = false
net_bridges = [
  [
    "vmbr1",
    "10.40.123.1",
    "24",
    true,
  ],
  [
    "vmbr2",
    "10.40.124.1",
    "24",
    true,
  ],
  [
    "vmbr3",
    "10.40.125.1",
    "24",
    true,
  ],
  [
    "vmbr4",
    "10.40.126.1",
    "24",
    true,
  ],
]
net_devs = [
  [
    "tap1-ceph",
    "vmbr1",
  ],
  [
    "tap2-ceph",
    "vmbr2",
  ],
  [
    "tap3-ceph",
    "vmbr3",
  ],
  [
    "tap4-ceph",
    "vmbr4",
  ],
]

[addon_postinstall]
joblist_early = []
joblist_late = [
  "/opt/umi/postinstall/installer/postinstall_ceph_install.bash",
  "/opt/umi/postinstall/manage/manage_ceph_pools.bash",
]
copy_additional_scripts = [
  "installer/postinstall_offline_packages.bash",
  "installer/postinstall_hostnetwork.bash",
  "installer/postinstall_apt.bash",
  "installer/postinstall_ssh.bash",
  "installer/postinstall_locale.bash",
]

[addon_answerfile]
host_name = "ceph"
host_domain = "local"
net_dhcp = true
net_ip = "10.40.123.100"
net_mask = "255.255.255.0"
net_gateway = "10.40.123.1"
net_dns = "8.8.8.8"
include_offline_packages = ["ifenslave", "vlan"]
packages_install = ["openssh-server"]

[[env]]
"ISO_TARGET_TYPE" = "vm"
"MANAGE_NET" = "10.40.123"
"MANAGE_IP" = "10.40.123.85"
"MANAGE_HOST" = "ceph-p4"
"MANAGE_DOMAIN" = "local"
"MANAGE_GW" = "10.40.123.1"
"MANAGE_NS1" = "8.8.8.8"
"MANAGE_NS2" = "8.8.4.4"
"PROXY_IP" = "10.40.123.1:3128"
"TIME_IP" = "10.40.123.1"
"STORAGE_NET" = "172.19.1"
"STORAGE_IP" = "172.19.1.91"
"HB_NET" = "172.18.1"
"HB_IP" = "172.18.1.85"
"BOND0_NAME" = "bond0"
"BOND1_NAME" = "bond1"
"BRIDGE0_NAME" = "vmbr0"
"BRIDGE1_NAME" = "vmbr1"
"INTERFACE_BACK" = "enp0s6"
"INTERFACE_BOND0" = "enp0s7"
"INTERFACE_BOND1" = "enp0s8"
"INTERFACE_CEPH" = "enp0s9"
"VLAN_STORAGE" = "210"
"VLAN_HEARTBEAT" = "209"
"INTERFACE_VLAN_STORAGE" = "vlan210"
"INTERFACE_VLAN_HEARTBEAT" = "vlan209"
"DISKNAME_PRIMARY" = "/dev/vda"
"CEPH_HOST_1" = "ceph-p1"
"CEPH_HOST_2" = "ceph-p2"
"CEPH_HOST_3" = "ceph-p3"
"CEPH_HOST_4" = "ceph-p4"
"CEPH_IP_1" = "172.19.1.93"
"CEPH_IP_2" = "172.19.1.95"
"CEPH_IP_3" = "172.19.1.97"
"CEPH_IP_4" = "172.19.1.99"
