[description]
name = "ceph-p5"

[addon_answerfile]
host_name = "ceph-p5"
host_domain = "local"
net_ip = "10.10.123.89"

[[env]]
"MANAGE_HOST" = "ceph-p5"
"MANAGE_IP" = "10.10.123.89"
"HB_IP" = "10.20.124.89"
"STORAGE_IP" = "10.20.125.89"

[run]
vmname = "ceph-p5"
net_devs = [
  [
    "tap1-cp5",
    "vmbr1",
  ],
  [
    "tap2-cp5",
    "vmbr2",
  ],
  [
    "tap3-cp5",
    "vmbr3",
  ],
  [
    "tap4-cp5",
    "vmbr4",
  ],
]
