[description]
name = "ceph-p10"

[addon_answerfile]
host_name = "ceph-p10"
host_domain = "local"
net_ip = "10.10.123.111"

[[env]]
"MANAGE_HOST" = "ceph-p10"
"MANAGE_IP" = "10.10.123.111"
"HB_IP" = "10.20.124.111"
"STORAGE_IP" = "10.20.125.111"

[run]
vmname = "ceph-p10"
net_devs = [
  [
    "tap1-cp10",
    "vmbr1",
  ],
  [
    "tap2-cp10",
    "vmbr2",
  ],
  [
    "tap3-cp10",
    "vmbr3",
  ],
  [
    "tap4-cp10",
    "vmbr4",
  ],
]
