[description]
name = "ceph-p8"

[addon_answerfile]
host_name = "ceph-p8"
host_domain = "local"
net_ip = "10.10.123.107"

[[env]]
"MANAGE_HOST" = "ceph-p8"
"MANAGE_IP" = "10.10.123.107"
"HB_IP" = "10.20.124.107"
"STORAGE_IP" = "10.20.125.107"

[run]
vmname = "ceph-p8"
net_devs = [
  [
    "tap1-cp8",
    "vmbr1",
  ],
  [
    "tap2-cp8",
    "vmbr2",
  ],
  [
    "tap3-cp8",
    "vmbr3",
  ],
  [
    "tap4-cp8",
    "vmbr4",
  ],
]
