
[description]
name = "ceph-p2"

[addon_answerfile]
host_name = "ceph-p2"
host_domain = "local"
net_ip = "10.40.123.87"

[run]
vmname = "ceph-p2"
net_prepare_fw = false
net_prepare_nics = true
net_prepare_bridges = false
net_ports = [[2222, 22]]
net_devs = [
  [
    "tap1-cp2",
    "vmbr1",
  ],
  [
    "tap2-cp2",
    "vmbr2",
  ],
  [
    "tap3-cp2",
    "vmbr3",
  ],
  [
    "tap4-cp2",
    "vmbr4",
  ],
]

[[env]]
"ISO_TARGET_TYPE" = "vm"
"MANAGE_NET" = "10.40.123"
"MANAGE_IP" = "10.40.123.87"
"MANAGE_HOST" = "ceph-p2"
"MANAGE_DOMAIN" = "local"
"MANAGE_GW" = "10.40.123.1"
"MANAGE_NS1" = "8.8.8.8"
"MANAGE_NS2" = "8.8.4.4"
"PROXY_IP" = "10.40.123.1:3128"
"TIME_IP" = "10.40.123.1"
"STORAGE_NET" = "10.40.125"
"STORAGE_IP" = "10.40.125.87"
"HB_NET" = "10.40.124"
"HB_IP" = "10.40.124.87"
"BOND0_NAME" = "bond0"
"BOND1_NAME" = "bond1"
"BRIDGE0_NAME" = "vmbr0"
"BRIDGE1_NAME" = "vmbr1"
"INTERFACE_BOND0_0" = "enp0s8"
"INTERFACE_BOND0_1" = "enp0s9"
"INTERFACE_BOND1_0" = "enp0s10"
"INTERFACE_BOND1_1" = "enp0s11"
"VLAN_STORAGE" = "210"
"VLAN_HEARTBEAT" = "209"
"INTERFACE_VLAN_STORAGE" = "vlan210"
"INTERFACE_VLAN_HEARTBEAT" = "vlan209"
"DISKNAME_PRIMARY" = "/dev/vda"
"CEPH_HOST_1" = "ceph-p1"
"CEPH_HOST_2" = "ceph-p2"
"CEPH_HOST_3" = "ceph-p3"
"CEPH_HOST_4" = "ceph-p4"
"CEPH_IP_1" = "10.40.125.85"
"CEPH_IP_2" = "10.40.125.87"
"CEPH_IP_3" = "10.40.125.89"
"CEPH_IP_4" = "10.40.125.91"
