[description]
name = "ceph-p3"

[addon_answerfile]
host_name = "ceph-p3"
host_domain = "local"
net_ip = "10.10.123.85"

[[env]]
"MANAGE_HOST" = "ceph-p3"
"MANAGE_IP" = "10.10.123.85"
"HB_IP" = "10.20.124.85"
"STORAGE_IP" = "10.20.125.85"

[run]
vmname = "ceph-p3"
net_devs = [
  [
    "tap1-cp3",
    "vmbr1",
  ],
  [
    "tap2-cp3",
    "vmbr2",
  ],
  [
    "tap3-cp3",
    "vmbr3",
  ],
  [
    "tap4-cp3",
    "vmbr4",
  ],
]
