
[description]
name = "mps"
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
path_postinstall = "postinstall"
file_postinstall = "postinstall.bash"

[run]
vmname = "mps-test"
net_ports = [[2220, 22]]

[addon_postinstall]
password_length = 24
password_charset = 'A-Za-z0-9!$%$&/()=?+*#-_.:,;<>' # No quotes and backslahes
joblist_late = ["/opt/umi/postinstall/installer/postinstall_mps.bash"]
copy_additional_scripts = ["installer/default/finalize.bash"]
exec_additional_scripts = [
  "installer/default/offline_packages.bash",
  "installer/default/hostnet_dhcp.bash",
  "installer/default/apt.bash",
  "installer/default/essentials.bash",
  "installer/default/user.bash",
  "installer/default/ssh.bash",
  "installer/default/locale.bash",
  # "installer/default/finalize.bash",
]
enable_grub_theme = true

[addon_grub]
grub_theme = "anon"
timeout = 0

[addon_answerfile]
host_name = "mps"
additional_users = ["user3", "user4", "user5"]
sudo_users = ["umi", "user3", "user4", "user5"]

[[env]]
"DEFAULT_HOST" = "mps"
"DEFAULT_DOMAIN" = "local"
"DEFAULT_NIC_0" = "enp0s2"
