
[description]
name = "mps1"
optional_params = { val1 = "mps1" }

[run]
vmname = "mps1"
net_ports = [[2221, 22]]
net_prepare_nics = true
net_prepare_bridges = false
net_devs = [["tap1-mps1", "vmbr0"], ["tap2-mps1", "vmbr0"]]

[addon_answerfile]
host_name = "mps1"
net_dhcp = true
