
[description]
name = "mpsdev"
config_version = "0.0.2"

[run]
vmname = "mpsdev"
net_devs = [["nat"]]
net_ports = [["2223", "22"]]

[addon_answerfile]
host_name = "mpsdev"

[target]
cmds = { "cmd1" = "ssh -p 2222 root@localhost echo hello", "cmd2" = "ssh -p 2222 root@localhost echo hello" }

[[env]]
"DEFAULT_HOST" = "mpsdev"
"DEFAULT_DOMAIN" = "local"
