
[description]
name = "mps"
virtio_name = ""
virtio_url = ""
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
answerfile = ""
path_postinstall = "postinstall"
file_postinstall = "postinstall.bash"

[run]
vmname = "mps-test"
disks = [
  [
    "os-hdd0.qcow2",
    "256G",
    "hdd",
    "none",
  ],
  [
    "data-hdd1.qcow2",
    "128G",
    "hdd",
    "none",
  ],
]
net_ports = [[2220, 22]]
net_devs = [["nat"]]

[addon_postinstall]
joblist_late = ["/opt/umi/postinstall/installer/postinstall_mps.bash"]
copy_additional_scripts = [
  "installer/default/hostnet_dhcp.bash",
  "installer/default/apt.bash",
  "installer/default/ssh.bash",
  "installer/default/locale.bash",
]
enable_grub_theme = true

[addon_grub]
grub_theme = "anon"

[addon_answerfile]
answerfile_enable_dhcp = true
answerfile_enable_crypto = true
host_name = "mps"
host_domain = "local"
packages_install = [
  "openssh-server",
  "build-essential",
  "vim",
  "git",
  "sudo",
  "make",
  "bc",
  "bsdmainutils",
  "debconf",
  "lsb-release",
  "fontconfig",
  "psmisc",
  "kitty",
  "tcpdump",
  "traceroute",
  "ntp",
  "gnupg",
  "curl",
  "wget",
  "gnupg",
  "dnsutils",
  "net-tools",
  "bridge-utils",
  "uml-utilities",
  "iftop",
  "sysstat",
]

[[env]]
"DEFAULT_HOST" = "mps"
"DEFAULT_DOMAIN" = "local"
"DEFAULT_NIC_0" = "enp0s2"
