[description]
name = "hive"
config_version = "0.0.9"

[run]
vmname = "hive"
net_devs = [["tap-mps1", "brMps", "c2:9c:4a:d7:83:33"]]
net_bridges = [["brMps", "10.10.100.1", "24", ""]]
net_ports = []
disks = [["disk1.qcow2", "256G", "hdd"]]
res_cpu = 16
res_mem = 18192

[addon_postinstall]
joblist_early = []
joblist_late = ["installer/postinstall_mps.bash"]
copy_additional_scripts = ["installer/default/finalize.bash"]
exec_additional_scripts = [
  "installer/default/hostnet_dhcp.bash",
  "installer/default/hostnames.bash",
  "installer/default/apt.bash",
  # "installer/default/docker.bash",
  # "installer/default/user.bash",
  # "installer/default/essentials.bash",
  # "installer/default/shell.bash",
  # "installer/default/ssh.bash",
  # "installer/default/locale.bash",
  # "installer/default/firewall.bash",
  # "installer/default/vim.bash",
]
enable_grub_theme = true

[addon_user]
user_enabled = true
default_user_dir = "umi"

[addon_grub]
grub_theme = "anon"
timeout = 0
sleeptime = 0

[addon_answerfile]
answerfile_enable_networking = false
answerfile_enable_dhcp = false
answerfile_enable_crypto = false
answerfile_enable_lvm = true
answerfile_confirm_partitioning = true
answerfile_confirm_final_reboot = false
install_disk = ""
user_root_pw = "rootpass"
user_other_name = "jb"
user_other_fullname = "jb"
user_other_pw = "jbpass"
disk_recipe = "simple"
host_name = "hivevm"
host_domain = "local"
net_dhcp = false
net_ip = ""
net_mask = ""
net_gateway = ""
net_dns = "8.8.8.8"
packages_install = ["openssh-server", "sudo"]
additional_users = ["deploy"]
sudo_users = ["deploy", "jb"]
admin_users = ["jb"]
config_users = ["jb"]
deployment_users = ["deploy"]
admin_group_name = "umi-admin"
config_group_name = "umi-config"
disk_password = "diskpass"
include_git_repositories = ["https://github.com/mpsffap/ansible-fragments.git"]
include_offline_packages = []
include_anna_packages = [
  "fdisk-udeb",
  "parted-udeb",
  "wget-udeb",
  "ssh-client-udeb",
]
preseed_commands_early = []
preseed_commands_late = []
ssh_installation_enabled = false
ssh_installation_breakpoint_pre = "" # Can be networking, partman, packages or grub
ssh_installation_breakpoint_post = "" # Can be networking, partman, packages or grub
# ssh_installation_password = "foobar"

[addon_cmd]
cmd_enabled = true
cmds = [
  { "name" = "cmd1", "scope" = "", "con" = "nat", "cmd" = "echo hello" },
  { "name" = "bash", "scope" = "", "con" = "nat", "cmd" = "bash -i" },
]

[addon_ssh]
ssh_enabled = true
config_auth_append = "~/.ssh/id_rsa.pub"

[[env]]
"DEFAULT_HOST" = "hive"
"DEFAULT_DOMAIN" = "local"
"DEFAULT_NIC_0" = "enp0s5"
# "DEFAULT_NIC_0" = "enp6s0"
# "DEFAULT_NIC_1" = "enp7s0"
"DOCKER_ROOT" = "/srv/docker"
# "DEFAULT_FW_POLICY_IN" = "DROP"
# "DEFAULT_FW_POLICY_OUT" = "ACCEPT"
# "DEFAULT_FW_POLICY_FWD" = "DROP"
# "DEFAULT_FW_PORTS_TCP" = "22"
# "DEFAULT_FW_PORTS_UDP" = ""
