
[description]
name = "mps"
iso_name = "debian-12.11.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.11.0-amd64-netinst.iso"
iso_type = "linux"
path_postinstall = "postinstall"
file_postinstall = "postinstall.bash"
enabled_overlays = ["mpsdev"]
config_version = "0.0.3"

[run]
vmname = "mps-test"
net_devs = [["nat"]]
net_ports = [["2224", "22"]]
disks = [["disk1.qcow2", "256G", "hdd"], ["disk2.qcow2", "256G", "hdd"]]

[addon_postinstall]
auto_updates = true
password_generate = false
password_length = 24
bash_aliases = ".bash_aliases"
password_charset = 'A-Za-z0-9!%$&=?+*#-_.:,;<>' # No quotes and backslahes
joblist_early = []
joblist_late = ["/opt/umi/postinstall/installer/postinstall_mps.bash"]
copy_additional_scripts = ["installer/default/finalize.bash"]
exec_additional_scripts = [
  "installer/default/hostnet_dhcp.bash",
  "installer/default/hostnames.bash",
  "installer/default/apt.bash",
  "installer/default/essentials.bash",
  "installer/default/shell.bash",
  "installer/default/user.bash",
  "installer/default/ssh.bash",
  "installer/default/locale.bash",
  "installer/default/docker.bash",
  "installer/default/firewall.bash",
]
enable_grub_theme = true

[addon_user]
user_enabled = true
default_user_dir = "umi"

[addon_grub]
grub_theme = "anon"
timeout = 30

[addon_answerfile]
answerfile_enable_networking = false
answerfile_enable_dhcp = false
answerfile_enable_crypto = true
answerfile_enable_lvm = true
answerfile_confirm_partitioning = true
answerfile_confirm_final_reboot = false
install_disk = ""
user_root_pw = "rootpass"
user_other_name = "mps"
user_other_fullname = "mps"
user_other_pw = "mpspass"
host_name = "mps"
host_domain = "local"
net_dhcp = false
net_ip = "10.23.42.9"
net_mask = "255.255.255.0"
net_gateway = "10.23.42.1"
net_dns = "8.8.8.8"
packages_install = ["openssh-server"]
additional_users = ["umi-admin"]
sudo_users = ["umi", "umi-admin"]
admin_users = ["umi-admin"]
admin_group_name = "admin"
disk_password = "diskpass"
include_git_repositories = ["https://github.com/odem/mps.git"]

[addon_cmd]
cmd_enabled = true
cmds = [
  { "name" = "cmd1", "scope" = "", "con" = "nat", "cmd" = "echo hello" },
  { "name" = "bash", "scope" = "", "con" = "nat", "cmd" = "bash -i" },
]

[addon_ssh]
ssh_enabled = true
config_auth_append = "~/.ssh/id_rsa_dummy.pub"

[[env]]
"DEFAULT_HOST" = "mps"
"DEFAULT_DOMAIN" = "local"
"DEFAULT_NIC_0" = "enp0s2"
"DOCKER_ROOT" = "/srv/docker"
"DEFAULT_FW_POLICY_IN" = "DROP"
"DEFAULT_FW_POLICY_OUT" = "ACCEPT"
"DEFAULT_FW_POLICY_FWD" = "DROP"
"DEFAULT_FW_PORTS_TCP" = "22"
"DEFAULT_FW_PORTS_UDP" = ""
