
[description]
name = "mps"
virtio_name = ""
virtio_url = ""
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://chuangtzu.ftp.acc.umu.se/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
answerfile = "preseed_dhcp.cfg"
path_postinstall = "postinstall"
file_postinstall = "postinstall.bash"

[run]
vmname = "mps-test"
net_ports = [[2220, 22]]
net_devs = [["tap1-mps1", "vmbr0"], ["tap2-mps1", "vmbr0"]]

[addon_postinstall]
copy_additional_scripts = [
  "postinstall_apt.bash",
  "postinstall_ssh.bash",
  "postinstall_locale.bash",
]

[addon_answerfile]
host_name = "debian12"
host_domain = "local"
net_dhcp = false
packages_install = [
  "openssh-server",
  "build-essential",
  "vim",
  "git",
  "make",
  "debconf",
  "sudo",
  "lsb-release",
  "net-tools",
  "psmisc",
  "dnsutils",
  "fontconfig",
  "curl",
  "gnupg",
  "bsdmainutils",
]
