
[description]
name = "xrdp"
virtio_name = ""
virtio_url = ""
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
answerfile = "preseed_on_lvm_dhcp.cfg"
path_postinstall = "postinstall"
file_postinstall = "postinstall.bash"

[run]
vmname = "xrdp-test"
net_ports = [[3389, 3389], [2222, 22]]


[addon_postinstall]
joblist_early = []
joblist_late = ["/opt/umi/postinstall/installer/postinstall_xrdp.bash"]
copy_additional_scripts = [
  "installer/default/offline_packages.bash",
  "installer/default/hostnet_dhcp.bash",
  "installer/default/hostnames.bash",
  "installer/default/apt.bash",
  "installer/default/essentials.bash",
  "installer/default/ssh.bash",
  "installer/default/locale.bash",
]

[addon_answerfile]
host_name = "xrdp"
host_domain = "local"
packages_install = ["openssh-server", "vim", "sudo", "net-tools"]
