
[description]
name = "xrdp"

[run]
vmname = "xfce-test"
net_ports = [[3390, 3389], [2224, 22]]

[addon_postinstall]
joblist_early = []
joblist_late = []
copy_additional_scripts = ["installer/default/finalize.bash"]
exec_additional_scripts = [
  "installer/default/hostnet_dhcp.bash",
  "installer/default/hostnames.bash",
  "installer/default/apt.bash",
  "installer/default/essentials.bash",
  "installer/default/shell.bash",
  "installer/default/user.bash",
  "installer/default/ssh.bash",
  "installer/default/locale.bash",
  "installer/default/firewall.bash",
  "installer/postinstall_xfce.bash",
  "installer/postinstall_xrdp.bash",
]

[addon_answerfile]
host_name = "xfce"
host_domain = "local"

[[env]]
"DEFAULT_HOST" = "xfce"
"DEFAULT_DOMAIN" = "local"
