
[description]
name = "proxmox-p6"

[addon_answerfile]
host_name = "proxmox-p6"
host_domain = "local"
net_ip = "10.10.123.103"

[[env]]
"MANAGE_HOST" = "proxmox-p6"
"MANAGE_IP" = "10.10.123.103"
"HB_IP" = "10.20.124.103"
"STORAGE_IP" = "10.20.125.103"

[run]
vmname = "proxmox-p6"
net_devs = [
  [
    "tap1-pp6",
    "vmbr1",
  ],
  [
    "tap2-pp6",
    "vmbr2",
  ],
  [
    "tap3-pp6",
    "vmbr3",
  ],
  [
    "tap4-pp6",
    "vmbr4",
  ],
]
