
[description]
name = "proxmox"
virtio_name = ""
virtio_url = ""
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
answerfile = "preseed_offline.cfg"
path_postinstall = "postinstall"
file_postinstall = "postinstall.bash"

[[optional_params]]
"ISO_TARGET_TYPE" = "vm"
"PROXMOX_IP" = "10.40.123.1"
"PROXMOX_HOST" = "nohost"
"PROXMOX_DOMAIN" = "nodomain"
"PROXMOX_GW" = "nogw"
"PROXMOX_NS1" = "nodns1"
"PROXMOX_NS2" = "nodns2"
"PROXY_IP" = "10.40.123.1:3128"
"TIME_IP" = "10.40.123.1"
"PROXMOX_NET" = "10.40.123"
"STORAGE_NET" = "172.19.1"
"STORAGE_IP" = "172.19.1.1"
"HB_NET" = "172.18.1"
"HB_IP" = "172.18.1.1"
"BOND0_NAME" = "bond0"
"BOND1_NAME" = "bond1"
"BRIDGE0_NAME" = "vmbr0"
"BRIDGE1_NAME" = "vmbr1"
"INTERFACE_BACK" = "iface0"
"INTERFACE_BOND0" = "iface1"
"INTERFACE_BOND1" = "iface2"
"INTERFACE_CEPH" = "iface3"
"VLAN_STORAGE" = "210"
"VLAN_HEARTBEAT" = "209"
"INTERFACE_VLAN_STORAGE" = "vlan210"
"INTERFACE_VLAN_HEARTBEAT" = "vlan209"
"DISKNAME_PRIMARY" = "/dev/vda"
"PROXMOX_HOST_1" = "proxmox-p1"
"PROXMOX_HOST_2" = "proxmox-p2"
"PROXMOX_HOST_3" = "proxmox-p3"
"PROXMOX_HOST_4" = "proxmox-p4"
"PROXMOX_IP_1" = "10.40.123.93"
"PROXMOX_IP_2" = "10.40.123.95"
"PROXMOX_IP_3" = "10.40.123.97"
"PROXMOX_IP_4" = "10.40.123.99"
"STORAGE_IP_1" = "172.19.1.93"
"STORAGE_IP_2" = "172.19.1.95"
"STORAGE_IP_3" = "172.19.1.97"
"STORAGE_IP_4" = "172.19.1.99"
"HB_IP_1" = "172.18.1.93"
"HB_IP_2" = "172.18.1.95"
"HB_IP_3" = "172.18.1.97"
"HB_IP_4" = "172.18.1.99"


[run]
vmname = "proxmoxbase"
net_prepare_fw = true
net_prepare_nics = true
net_prepare_bridges = true
net_ports = [[2220, 22]]
net_bridges = [
  [
    "vmbr1",
    "10.40.123.1",
    "24",
    true,
  ],
  [
    "vmbr2",
    "10.40.124.1",
    "24",
    true,
  ],
  [
    "vmbr3",
    "10.40.125.1",
    "24",
    true,
  ],
  [
    "vmbr4",
    "10.40.126.1",
    "24",
    true,
  ],
]
net_devs = [
  [
    "tap1-mps",
    "vmbr1",
  ],
  [
    "tap2-mps",
    "vmbr2",
  ],
  [
    "tap3-mps",
    "vmbr3",
  ],
  [
    "tap4-mps",
    "vmbr4",
  ],
]

[addon_postinstall]
joblist_early = []
joblist_late = [
  "/opt/umi/postinstall/manage/manage_proxmox_localpools.bash",
  "/opt/umi/postinstall/manage/manage_proxmox_sdn.bash",
]
copy_additional_scripts = [
  "postinstall_offline_packages.bash",
  "postinstall_hostnetwork.bash",
  "postinstall_apt.bash",
  "postinstall_ssh.bash",
  "postinstall_locale.bash",
]
enable_grub_theme = true

[addon_grub]
grub_theme = "anon"

[addon_answerfile]
host_name = "debian12"
host_domain = "local"
net_dhcp = true
net_ip = "10.40.123.100"
net_mask = "255.255.255.0"
net_gateway = "10.40.123.1"
net_dns = "10.40.123.1"
include_offline_packages = ["ifenslave", "vlan"]
packages_install = [
  "openssh-server",
  "build-essential",
  "vim",
  "git",
  "make",
  "debconf",
  "sudo",
  "lsb-release",
  "net-tools",
  "psmisc",
  "dnsutils",
  "fontconfig",
  "curl",
  "gnupg",
  "bsdmainutils",
]
