
[description]
name = "proxmox-p5"

[addon_answerfile]
host_name = "proxmox-p5"
host_domain = "local"
net_ip = "10.10.123.101"

[[env]]
"MANAGE_HOST" = "proxmox-p5"
"MANAGE_IP" = "10.10.123.101"
"HB_IP" = "10.20.124.101"
"STORAGE_IP" = "10.20.125.101"

[run]
vmname = "proxmox-p5"
net_devs = [
  [
    "tap1-pp5",
    "vmbr1",
  ],
  [
    "tap2-pp5",
    "vmbr2",
  ],
  [
    "tap3-pp5",
    "vmbr3",
  ],
  [
    "tap4-pp5",
    "vmbr4",
  ],
]
