
[description]
name = "proxmox-p1"

[addon_answerfile]
host_name = "proxmox-p1"
host_domain = "local"
net_ip = "10.10.123.93"

[[env]]
"MANAGE_HOST" = "proxmox-p1"
"MANAGE_IP" = "10.10.123.93"
"HB_IP" = "10.20.124.93"
"STORAGE_IP" = "10.20.125.93"

[run]
vmname = "proxmox-p1"
net_devs = [
  [
    "tap1-pp1",
    "vmbr1",
  ],
  [
    "tap2-pp1",
    "vmbr2",
  ],
  [
    "tap3-pp1",
    "vmbr3",
  ],
  [
    "tap4-pp1",
    "vmbr4",
  ],
]
