
[description]
name = "proxmox-p4"

[addon_answerfile]
host_name = "proxmox-p4"
host_domain = "local"
net_ip = "10.10.123.99"

[[env]]
"MANAGE_HOST" = "proxmox-p4"
"MANAGE_IP" = "10.10.123.99"
"HB_IP" = "10.20.124.99"
"STORAGE_IP" = "10.20.125.99"

[run]
vmname = "proxmox-p4"
net_devs = [
  [
    "tap1-pp4",
    "vmbr1",
  ],
  [
    "tap2-pp4",
    "vmbr2",
  ],
  [
    "tap3-pp4",
    "vmbr3",
  ],
  [
    "tap4-pp4",
    "vmbr4",
  ],
]
