
[description]
name = "proxmox"
virtio_name = ""
virtio_url = ""
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
answerfile = "preseed_off_no_enc.cfg"
path_postinstall = "postinstall"
file_postinstall = "postinstall.bash"

[run]
vmname = "proxmoxbase"
net_prepare_fw = true
net_prepare_nics = true
net_prepare_bridges = false
res_cpu = 2
res_mem = 2048
disks = [
  [
    "os-hdd0.qcow2",
    "64G",
    "hdd",
    "none",
  ],
  [
    "ceph-hdd1.qcow2",
    "64G",
    "hdd",
    "none",
  ],
  [
    "ceph-hdd2.qcow2",
    "64G",
    "hdd",
    "none",
  ],
  [
    "ceph-nvme1.raw",
    "32G",
    "nvme",
    "none",
  ],
  [
    "ceph-nvme2.raw",
    "32G",
    "nvme",
    "none",
  ],
]
net_bridges = [
  [
    "vmbr1",
    "10.10.123.1",
    "24",
    true,
  ],
  [
    "vmbr2",
    "10.10.124.1",
    "24",
    true,
  ],
  [
    "vmbr3",
    "10.10.125.1",
    "24",
    true,
  ],
  [
    "vmbr4",
    "10.10.126.1",
    "24",
    true,
  ],
]
net_devs = [
  [
    "tap1-proxmox",
    "vmbr1",
  ],
  [
    "tap2-proxmox",
    "vmbr2",
  ],
  [
    "tap3-proxmox",
    "vmbr3",
  ],
  [
    "tap4-proxmox",
    "vmbr4",
  ],
]

[addon_grub]
grub_kernel_lvm_alt1 = "6.2.16-20-pve"
grub_kernel_lvm_alt2 = "6.8.12-10-pve"

[addon_postinstall]
joblist_early = []
joblist_late = [
  "/opt/umi/postinstall/installer/postinstall_proxmox_install.bash",
  "/opt/umi/postinstall/manage/manage_ceph_cluster_hyper.bash",
  "/opt/umi/postinstall/manage/manage_proxmox_localpools.bash",
  "/opt/umi/postinstall/manage/manage_proxmox_sdn.bash",
]
copy_additional_scripts = [
  "installer/default/offline_packages.bash",
  "installer/cluster/hostnet.bash",
  "installer/cluster/hostnames.bash",
  "installer/cluster/apt.bash",
  "installer/default/ssh.bash",
  "installer/default/locale.bash",
]

[addon_answerfile]
host_name = "proxmox-p1"
host_domain = "local"
net_dhcp = true
net_ip = "10.10.123.100"
net_mask = "255.255.255.0"
net_gateway = "10.10.123.1"
net_dns = "8.8.8.8"
include_offline_packages = ["ifenslave", "vlan"]
packages_install = ["openssh-server"]

[[env]]
"ISO_TARGET_TYPE" = "vm"
"MANAGE_NET" = "10.10.123"
"MANAGE_IP" = "10.10.123.93"
"MANAGE_HOST" = "proxmox-p1"
"MANAGE_DOMAIN" = "local"
"MANAGE_GW" = "10.10.123.1"
"MANAGE_NS1" = "8.8.8.8"
"MANAGE_NS2" = "8.8.4.4"
"PROXY_IP" = "10.10.123.1:3128"
"TIME_IP" = "10.10.123.1"
"STORAGE_NET" = "10.20.125"
"STORAGE_IP" = "10.20.125.93"
"HB_NET" = "10.20.124"
"HB_IP" = "10.20.124.93"
"BOND0_NAME" = "bond0"
"BOND1_NAME" = "bond1"
"BRIDGE0_NAME" = "vmbr0"
"BRIDGE1_NAME" = "vmbr1"
"INTERFACE_BOND0_0" = "enp0s10"
"INTERFACE_BOND0_1" = "enp0s11"
"INTERFACE_BOND1_0" = "enp0s12"
"INTERFACE_BOND1_1" = "enp0s13"
"VLAN_HEARTBEAT" = "124"
"VLAN_STORAGE" = "125"
"INTERFACE_VLAN_HEARTBEAT" = "vlan124"
"INTERFACE_VLAN_STORAGE" = "vlan125"
"DISKNAME_PRIMARY" = "/dev/vda"
"DEFAULT_LEADER_PROXMOX" = "proxmox-p1"
"DEFAULT_LEADER_CEPH" = "ceph-p1"
"NODES_PROX_MANAGE_FQDN" = "proxmox-p1.local,proxmox-p2.local,proxmox-p3.local,proxmox-p4.local,proxmox-p5.local,proxmox-p6.local"
"NODES_PROX_MANAGE_NAME" = "proxmox-p1,proxmox-p2,proxmox-p3,proxmox-p4,proxmox-p5,proxmox-p6"
"NODES_PROX_MANAGE_IP" = "10.10.123.93,10.10.123.95,10.10.123.97,10.10.123.99,10.10.123.101,10.10.123.103"
"NODES_PROX_HB_FQDN" = "proxmox-p1.local,proxmox-p2.local,proxmox-p3.local,proxmox-p4.local,proxmox-p5.local,proxmox-p6.local"
"NODES_PROX_HB_NAME" = "proxmox-p1,proxmox-p2,proxmox-p3,proxmox-p4,proxmox-p5,proxmox-p6"
"NODES_PROX_HB_IP" = "10.20.124.93,10.20.124.95,10.20.124.97,10.20.124.99,10.20.124.101,10.20.124.103"
"NODES_PROX_STORAGE_FQDN" = "proxmox-p1.local,proxmox-p2.local,proxmox-p3.local,proxmox-p4.local,proxmox-p5.local,proxmox-p6.local"
"NODES_PROX_STORAGE_NAME" = "proxmox-p1,proxmox-p2,proxmox-p3,proxmox-p4,proxmox-p5,proxmox-p6"
"NODES_PROX_STORAGE_IP" = "10.20.125.93,10.20.125.95,10.20.125.97,10.20.125.99,10.20.125.101,10.20.125.103"
"NODES_CEPH_MANAGE_FQDN" = "ceph-p1.local,ceph-p2.local,ceph-p3.local,ceph-p4.local,ceph-p5.local,ceph-p6.local"
"NODES_CEPH_MANAGE_NAME" = "ceph-p1,ceph-p2,ceph-p3,ceph-p4,ceph-p5,ceph-p6"
"NODES_CEPH_MANAGE_IP" = "10.10.123.81,10.10.123.83,10.10.123.85,10.10.123.87,10.10.123.89,10.10.123.91"
"NODES_CEPH_HB_FQDN" = "ceph-p1.local,ceph-p2.local,ceph-p3.local,ceph-p4.local,ceph-p5.local,ceph-p6.local"
"NODES_CEPH_HB_NAME" = "ceph-p1,ceph-p2,ceph-p3,ceph-p4,ceph-p5,ceph-p6"
"NODES_CEPH_HB_IP" = "10.20.124.81,10.20.124.83,10.20.124.85,10.20.124.87,10.20.124.89,10.20.124.91"
"NODES_CEPH_STORAGE_FQDN" = "ceph-p1.local,ceph-p2.local,ceph-p3.local,ceph-p4.local,ceph-p5.local,ceph-p6.local"
"NODES_CEPH_STORAGE_NAME" = "ceph-p1,ceph-p2,ceph-p3,ceph-p4,ceph-p5,ceph-p6"
"NODES_CEPH_STORAGE_IP" = "10.20.125.81,10.20.125.83,10.20.125.85,10.20.125.87,10.20.125.89,10.20.125.91"
