
[description]
name = "proxmox-p3"

[addon_answerfile]
host_name = "proxmox-p3"
host_domain = "local"
net_ip = "10.10.123.97"

[[env]]
"MANAGE_HOST" = "proxmox-p3"
"MANAGE_IP" = "10.10.123.97"
"HB_IP" = "10.20.124.97"
"STORAGE_IP" = "10.20.125.97"

[run]
vmname = "proxmox-p3"
net_devs = [
  [
    "tap1-pp3",
    "vmbr1",
  ],
  [
    "tap2-pp3",
    "vmbr2",
  ],
  [
    "tap3-pp3",
    "vmbr3",
  ],
  [
    "tap4-pp3",
    "vmbr4",
  ],
]
