
[description]
name = "proxmox-p2"

[addon_answerfile]
host_name = "proxmox-p2"
host_domain = "local"
net_ip = "10.10.123.95"

[[env]]
"MANAGE_HOST" = "proxmox-p2"
"MANAGE_IP" = "10.10.123.95"
"HB_IP" = "10.20.124.95"
"STORAGE_IP" = "10.20.125.95"

[run]
vmname = "proxmox-p2"
net_devs = [
  [
    "tap1-pp2",
    "vmbr1",
  ],
  [
    "tap2-pp2",
    "vmbr2",
  ],
  [
    "tap3-pp2",
    "vmbr3",
  ],
  [
    "tap4-pp2",
    "vmbr4",
  ],
]
