
[description]
name = "offline"
virtio_name = ""
virtio_url = ""
iso_name = "debian-12.10.0-amd64-netinst.iso"
iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"
iso_type = "linux"
answerfile = "preseed_fixip.cfg"
path_postinstall = ""
file_postinstall = "postinstall.bash"

[run]
vmname = "offline-test"
net_prepare_fw = true
net_prepare_nics = true
net_prepare_bridges = true
net_ports = [[2220, 22]]
uplink_device = "enx04b9e3c01ac6"
net_bridges = [
  [
    "vmbr1",
    "10.40.121.1",
    "24",
    true,
  ],
  [
    "vmbr2",
    "10.40.122.1",
    "24",
    true,
  ],
  [
    "vmbr3",
    "10.40.123.1",
    "24",
    true,
  ],
  [
    "vmbr4",
    "10.40.124.1",
    "24",
    true,
  ],
]
net_devs = [
  [
    "tap1-mps",
    "vmbr1",
  ],
  [
    "tap2-mps",
    "vmbr2",
  ],
  [
    "tap3-mps",
    "vmbr3",
  ],
  [
    "tap4-mps",
    "vmbr4",
  ],
]
[addon_answerfile]
host_name = "offline"
host_domain = "local"
net_dhcp = false
net_ip = "10.40.121.100"
net_mask = "255.255.255.0"
net_gateway = "10.40.121.1"
net_dns = "8.8.8.8"
include_offline_packages = ["ifenslave"]
packages_install = [
  "openssh-server",
  "build-essential",
  "vim",
  "git",
  "make",
  "debconf",
  "sudo",
  "lsb-release",
  "net-tools",
  "psmisc",
  "dnsutils",
  "fontconfig",
  "curl",
  "gnupg",
  "bsdmainutils",
]

[addon_postinstall]
joblist_early = []
joblist_late = []
copy_additional_scripts = [
  "postinstall_offline_packages.bash",
  "postinstall_apt.bash",
  "postinstall_ssh.bash",
  "postinstall_locale.bash",
]
