interface=brMps
no-resolv
server=8.8.8.8
bind-interfaces
dhcp-range=10.10.100.100,10.10.100.200,255.255.255.0,12h
dhcp-option=3,10.10.100.1
dhcp-option=6,10.10.100.1
# IP via MAC
dhcp-host=c2:9c:4a:d7:83:33,10.10.100.180,hivevm,24h

# Logging
log-dhcp
log-queries
log-facility=/var/log/dnsmasq.log

